const weatherBank = {
	'01d': {
		weatherType: 'clear sky day',
		playlistId: '6pmTSyoGP89kpnzaSzQW4C',
		playlistTheme: 'white',
		weatherPhotoSearch: 'sunlight',
		},
	'01n': {
		weatherType: 'clear sky night',
		playlistId: '6pmTSyoGP89kpnzaSzQW4C',
		playlistTheme: 'black',
		weatherPhotoSearch: 'starry-night',
		},
	'02d': {
		weatherType: 'few clouds day',
		playlistId: '6muyGzSo8MyUsIIMGqJSna',
		playlistTheme: 'white',
		weatherPhotoSearch: 'cloudy',
		},
	'02n': {
		weatherType: 'few clouds night',
		playlistId: '6muyGzSo8MyUsIIMGqJSna',
		playlistTheme: 'black',
		weatherPhotoSearch: 'night-cloud',
		},
	'03d': {
		weatherType: 'scattered clouds day',
		playlistId: '6muyGzSo8MyUsIIMGqJSna',
		playlistTheme: 'white',
		weatherPhotoSearch: 'overcast',
		},
	'03n': {
		weatherType: 'scattered clouds night',
		playlistId: '6muyGzSo8MyUsIIMGqJSna',
		playlistTheme: 'black',
		weatherPhotoSearch: 'overcast',
		},
	'04d': {
		weatherType: 'broken clouds day',
		playlistId: '6muyGzSo8MyUsIIMGqJSna',
		playlistTheme: 'white',
		weatherPhotoSearch: 'clouds',
		},
	'04n': {
		weatherType: 'broken clouds night',
		playlistId: '6muyGzSo8MyUsIIMGqJSna',
		playlistTheme: 'black',
		weatherPhotoSearch: 'dark-cloud',
		},
	'09d': {
		weatherType: 'shower rain day',
		playlistId: '0NiHg73PvXtUQw9tB87kNW',
		playlistTheme: 'white',
		weatherPhotoSearch: 'raining',
		},
	'09n': {
		weatherType: 'shower rain night',
		playlistId: '0NiHg73PvXtUQw9tB87kNW',
		playlistTheme: 'black',
		weatherPhotoSearch: 'raining-night',
		},
	'10d': {
		weatherType: 'rain day',
		playlistId: '0NiHg73PvXtUQw9tB87kNW',
		playlistTheme: 'white',
		weatherPhotoSearch: 'rain',
		},
	'10n': {
		weatherType: 'rain night',
		playlistId: '0NiHg73PvXtUQw9tB87kNW',
		playlistTheme: 'black',
		weatherPhotoSearch: 'rain-night',
		},
	'11d': {
		weatherType: 'thunderstorm day',
		playlistId: '6mkMaOMvWbug59jXdRJnoo',
		playlistTheme: 'white',
		weatherPhotoSearch: 'thunderstorm',
		},
	'11n': {
		weatherType: 'thunderstorm night',
		playlistId: '6mkMaOMvWbug59jXdRJnoo',
		playlistTheme: 'black',
		weatherPhotoSearch: 'thunder',
		},
	'13d': {
		weatherType: 'snow day',
		playlistId: '3i9S8jLFZdwZZyJbgk4HHa',
		playlistTheme: 'white',
		weatherPhotoSearch: 'snowing',
		},
	'13n': {
		weatherType: 'snow night',
		playlistId: '3i9S8jLFZdwZZyJbgk4HHa',
		playlistTheme: 'black',
		weatherPhotoSearch: 'snow-night',
		},
	'50d': {
		weatherType: 'mist day',
		playlistId: '0kdgMdlV7dTeeslqXPrEuF',
		playlistTheme: 'white',
		weatherPhotoSearch: 'mist',
		},
	'50n': {
		weatherType: 'mist night',
		playlistId: '0kdgMdlV7dTeeslqXPrEuF',
		playlistTheme: 'black',
		weatherPhotoSearch: 'fog',
		},
}